---
- name: Debezium and ksqlDB

  hosts: all

  gather_facts: false

  become: true

  # allowing logs to be printed on the console can expose sensitive information
  # when deploying to production via CI/CD
  no_log: false

  # Enable the following vars if you are using WarpStream
  #vars:
    # Deinfe your WarpStream details here
    #warpstream_api_key: aks_xxxxxxxxxxxx
    #warpstream_cluster_id: vci_xxxxxxxxxxxx
    #warpstream_s3_bucket: "xxxxxxxxxxxx"

  roles:
    - debezium # Any sources, usually mariadb
