---
- name: Debezium and ksqlDB

  hosts: all

  gather_facts: false

  become: true

  # allowing logs to be printed on the console can expose sensitive information
  # when deploying to production via CI/CD
  no_log: false

  vars:
    # Deinfe your WarpStream details here
    warpstream_api_key: aks_xxxxx
    warpstream_cluster_id: vci_xxxxx
    warpstream_s3_bucket: "my-bucket"

  roles:
    - debezium # Any sources, usually mariadb