---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install some requirements
  apt:
    name:
      - jq # nice to have
      - openjdk-11-jre
      - openjdk-11-jdk
      - unzip
    state: present

- name: Create kafka destination folder
  file:
    path: /home/ubuntu/kafka
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Download kafka tgz file
  get_url:
    url: "https://downloads.apache.org/kafka/3.4.1/kafka_2.13-3.4.1.tgz"
    dest: /home/ubuntu/kafka.tgz

- name: Uncompress kafka.tgz file
  unarchive:
    src: /home/ubuntu/kafka.tgz
    dest: /home/ubuntu/kafka/
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Download mysql connector
  get_url:
    url: "https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.1.2.Final/debezium-connector-mysql-2.1.2.Final-plugin.tar.gz"
    dest: /home/ubuntu/debezium-connector-mysql.tgz

- name: Uncompress mysql connector .tgz file
  unarchive:
    src: /home/ubuntu/debezium-connector-mysql.tgz
    dest: /usr/share/java/
    remote_src: yes

- name: Create destination folder for redis connector
  file:
    path: /usr/share/java/kafka-connect-redis
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Check if files exist in the remote folder
  find:
    paths: /usr/share/java/kafka-connect-redis
  register: files

- name: Upload redis connector zip if files not already in place
  copy:
    src: kafka-connect-redis.zip
    dest: /home/ubuntu/kafka-connect-redis.zip
  when: files.matched == 0

- name: Unzip redis connector zip if files not already in place
  unarchive:
    src: /home/ubuntu/kafka-connect-redis.zip
    dest: /usr/share/java/kafka-connect-redis
    remote_src: yes
  when: files.matched == 0

- name: Upload the service file
  copy:
    src: debezium.service
    dest: /etc/systemd/system/debezium.service
    mode: "0644"
    owner: "root"
    group: "root"
  register: upload_result

- name: Upload and interpolate template
  template:
    src: connect-distributed.properties.j2
    dest: /home/ubuntu/kafka/config/connect-distributed.properties
    owner: root
    group: root
    mode: "0644"

- name: Perform systemctl daemon-reload
  systemd:
    name: ""
    daemon_reload: yes
  when: upload_result.changed

- name: Start debezium service
  service:
    name: debezium
    state: started
    enabled: yes
  when: upload_result.changed