---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install some requirements
  apt:
    name:
      - openjdk-11-jre
      - openjdk-11-jdk
      - software-properties-common
      - curl
      - gnupg
    state: present

- name: Add APT key
  apt_key:
    url: http://ksqldb-packages.s3.amazonaws.com/deb/0.28/archive.key
    state: present

- name: Add APT repository
  apt_repository:
    repo: "deb http://ksqldb-packages.s3.amazonaws.com/deb/0.28 stable main"
    state: present

- name: Update package cache
  apt:
    update_cache: yes

- name: Install confluent-ksqldb package
  apt:
    name: confluent-ksqldb
    state: present

- name: Upload the service file
  copy:
    src: ksqldb.service
    dest: /etc/systemd/system/ksqldb.service
    mode: "0644"
    owner: "root"
    group: "root"
  register: upload_result

- name: Perform systemctl daemon-reload
  systemd:
    name: ""
    daemon_reload: yes
  when: upload_result.changed

- name: Upload and interpolate template
  template:
    src: ksql-server.properties.j2
    dest: /etc/ksqldb/ksql-server.properties
    owner: root
    group: root
    mode: "0644"

- name: Start ksqldb service
  service:
    name: ksqldb
    state: started
    enabled: yes
  when: upload_result.changed

- set_fact:
    # define the topic to create a stream from
    topic: "example.my_database.users"

  # Read in the ksql query from a file
- set_fact:
    file_content: "{{ lookup('template', 'queries.ksql.j2', vars={topic: topic}) }}"

# Encapsulate the query with a ksql key
# This results in a body of {"ksql":"the actual query"}
- set_fact:
    body_content:
      ksql: "{{ file_content }}"

# Perform a Post request to submit the ksql to ksqldb
- name: Submit the ksql query to ksqldb
  ansible.builtin.uri:
    url: http://localhost:8088/ksql
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ body_content }}"
    status_code:
      - 200
      - 201
  register: result

# Sometimes Posting the query fails, show the error message
- name: Debug submitting the query to ksqldb
  ansible.builtin.debug:
    var: result