---
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install some requirements
      apt:
        name:
          - jq # nice to have
          - openjdk-11-jre
          - openjdk-11-jdk
        state: present
