- name: Check if file exists
  stat:
    path: /home/ubuntu/warpstream_agent_linux_arm64_latest.tar.gz
  register: file_stat

- name: Download file if not exists
  get_url:
    url: "https://warpstream-public-us-east-1.s3.amazonaws.com/warpstream_agent_releases/warpstream_agent_linux_arm64_latest.tar.gz"
    dest: /home/ubuntu/warpstream_agent_linux_arm64_latest.tar.gz
  when: not file_stat.stat.exists

- name: Ensure directory exists
  file:
    path: /home/ubuntu/.warpstream
    state: directory

- name: Extract .tar.gz file
  unarchive:
    src: /home/ubuntu/warpstream_agent_linux_arm64_latest.tar.gz
    dest: /home/ubuntu/.warpstream/
    remote_src: yes

- name: Upload service template file
  template:
    src: templates/warpstream.service.j2
    dest: /etc/systemd/system/warpstream.service
    owner: root
    group: root
    mode: 0644
  register: upload_result

- name: Perform systemctl daemon-reload
  systemd:
    name: ""
    daemon_reload: yes
  when: upload_result.changed

- name: Start warpstream service
  service:
    name: warpstream
    state: started
    enabled: yes
  when: upload_result.changed
